name: cmake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Install deps
      run: git clone https://github.com/kiddersmxj/std-k; cd std-k; bash install.sh; cd ..
    - name: Build using CMake
      run: ./install.sh

